package com.clancey.apollo.common.constant;

/**
 * @author ChenShuai
 * @date 2018/8/22 11:07
 */
public enum CodeEnum {
    /**
     * PRODUCT:商品编码
     * PRODUCT_INFO:商品信息编码
     * SUPPLIER_BILL_CODE 对账单号
     * XJ_CODE : 询价单号
     * YPJC_CODE:样品检测服务单号
     * PURCHASE_CODE : 采购单号
     * CUS_CODE  ： 客诉单号
     * CLIENT_BILL_CODE_FOR_MOUTH : 客户月结对账单号
     * CLIENT_BILL_CODE_FOR_ORDER ： 客户订单结对账单号
     * CRM_CLIENT_ORGANIZATION_CODE:  客户组织编码
     * FINANCIAL_INFORMATION_CODE    客户合同审核编码
     * SUPPLIER_CONTRACT_DB_CODE  供应商单笔合同编码
     * SUPPLIER_CONTRACT_CODE   供应商标准合同编码
     * SUPPLIER_CONTRACT_BM_CODE 供应商合同保密协议
     */
    EXAMPLE, EXAMPLE_NO_DATE, CREDIT, CREDIT_NO_DATE, CLIENT, CLIENT_WAREHOUSE, CLIENT_COMPACT,CLIENT_ORDER,PROOFING_APPLY,STRUCT_APPLY,VISION_APPLY,
    PRODUCT, PRODUCT_INFO, ORDER_BAG_SPLIT,SUPPLIER_BILL_CODE, XJ_CODE,YPJC_CODE, PURCHASE_CODE,CUS_CODE,CLIENT_BILL_FOR_MOUTH, CLIENT_BILL_FOR_ORDER,
    SE,CRM_CLIENT_ORGANIZATION_CODE, FINANCIAL_INFORMATION_CODE,PACKAGING,SUPPLIER_CONTRACT_DB_CODE,SUPPLIER_CONTRACT_CODE,SUPPLIER_CONTRACT_BM_CODE,SUPPLY;


}
